### ISSUE TITLE
Autosplitter no longer working on current version

### ISSUE THREAD

**Issue by fuhrmannb** [Dalet/LiveSplit.Wrack#1]
This autosplitter looks nice to speedrun the game but it seems to not work anymore with the current version. Is it possible to make it work?

Note: Wrack has been chosen into the Ultimate Decathlon 7 speedrun tournament, it would be fantastic that runners can use it :D

Thanks for your work.

**Comment by Dalet** [comment]
I'm excited to see people speedrunning this game again ! I'll see what I can do next week.
________________________________
